In [1]:
# Step 1 : import library
import pandas as pd
import numpy as np


In [4]:
# Step 2 : import data
wine = pd.read_csv('/content/WineQT.csv')

In [6]:
wine.head()

fixed acidity  volatile acidity  citric acid  residual sugar  chlorides  \
0            7.4              0.70         0.00             1.9      0.076   
1            7.8              0.88         0.00             2.6      0.098   
2            7.8              0.76         0.04             2.3      0.092   
3           11.2              0.28         0.56             1.9      0.075   
4            7.4              0.70         0.00             1.9      0.076   

   free sulfur dioxide  total sulfur dioxide  density    pH  sulphates  \
0                 11.0                  34.0   0.9978  3.51       0.56   
1                 25.0                  67.0   0.9968  3.20       0.68   
2                 15.0                  54.0   0.9970  3.26       0.65   
3                 17.0                  60.0   0.9980  3.16       0.58   
4                 11.0                  34.0   0.9978  3.51       0.56   

   alcohol  quality  Id  
0      9.4        5   0  
1      9.8        5   1  
2      9.8        5   2  
3      9.8        6   3  
4      9.4        5   4

In [7]:
wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1143 entries, 0 to 1142
Data columns (total 13 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   fixed acidity         1143 non-null   float64
 1   volatile acidity      1143 non-null   float64
 2   citric acid           1143 non-null   float64
 3   residual sugar        1143 non-null   float64
 4   chlorides             1143 non-null   float64
 5   free sulfur dioxide   1143 non-null   float64
 6   total sulfur dioxide  1143 non-null   float64
 7   density               1143 non-null   float64
 8   pH                    1143 non-null   float64
 9   sulphates             1143 non-null   float64
 10  alcohol               1143 non-null   float64
 11  quality               1143 non-null   int64  
 12  Id                    1143 non-null   int64  
dtypes: float64(11), int64(2)
memory usage: 116.2 KB


In [12]:
wine.describe()

fixed acidity  volatile acidity  citric acid  residual sugar  \
count    1143.000000       1143.000000  1143.000000     1143.000000   
mean        8.311111          0.531339     0.268364        2.532152   
std         1.747595          0.179633     0.196686        1.355917   
min         4.600000          0.120000     0.000000        0.900000   
25%         7.100000          0.392500     0.090000        1.900000   
50%         7.900000          0.520000     0.250000        2.200000   
75%         9.100000          0.640000     0.420000        2.600000   
max        15.900000          1.580000     1.000000       15.500000   

         chlorides  free sulfur dioxide  total sulfur dioxide      density  \
count  1143.000000          1143.000000           1143.000000  1143.000000   
mean      0.086933            15.615486             45.914698     0.996730   
std       0.047267            10.250486             32.782130     0.001925   
min       0.012000             1.000000              6.000000     0.990070   
25%       0.070000             7.000000             21.000000     0.995570   
50%       0.079000            13.000000             37.000000     0.996680   
75%       0.090000            21.000000             61.000000     0.997845   
max       0.611000            68.000000            289.000000     1.003690   

                pH    sulphates      alcohol      quality           Id  
count  1143.000000  1143.000000  1143.000000  1143.000000  1143.000000  
mean      3.311015     0.657708    10.442111     5.657043   804.969379  
std       0.156664     0.170399     1.082196     0.805824   463.997116  
min       2.740000     0.330000     8.400000     3.000000     0.000000  
25%       3.205000     0.550000     9.500000     5.000000   411.000000  
50%       3.310000     0.620000    10.200000     6.000000   794.000000  
75%       3.400000     0.730000    11.100000     6.000000  1209.500000  
max       4.010000     2.000000    14.900000     8.000000  1597.000000

In [15]:
wine.shape

(1143, 13)

In [17]:
# Step 3 : define target (y) and features (X)
wine.columns

Index(['fixed acidity', 'volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide', 'total sulfur dioxide', 'density',
       'pH', 'sulphates', 'alcohol', 'quality', 'Id'],
      dtype='object')

In [29]:
y=wine['quality']


In [31]:
X = wine[['fixed acidity','volatile acidity', 'citric acid', 'residual sugar',
       'chlorides', 'free sulfur dioxide','total sulfur dioxide','density','pH','sulphates',
         'alcohol','quality']]

In [32]:
# Step 4 : train test split
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X,y, train_size=0.7, random_state=2529)

In [33]:
# check shape of train and test sample
X_train.shape, X_test.shape, y_train.shape, y_test.shape

((800, 12), (343, 12), (800,), (343,))

In [34]:
# Step 5 : select model
from sklearn.linear_model import LogisticRegression
model = LogisticRegression(max_iter=5000)

In [35]:
# Step 6 : train or fit model
model.fit(X_train,y_train)

/usr/local/lib/python3.10/dist-packages/sklearn/linear_model/_logistic.py:458: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


LogisticRegression(max_iter=5000)

In [38]:
model.intercept_

array([ 38.18946111,  33.81318963,  30.19959026,  -5.68173869,
       -41.76878318, -54.75171913])

In [39]:
model.coef_

array([[-1.27217801e-01,  1.11371827e+00, -6.34705013e-02,
         1.58367515e-01,  1.03426332e-01,  1.20305858e-04,
        -3.82438401e-02,  2.46104092e-02,  1.60441395e-01,
        -1.25884870e-01, -6.01761882e-01, -5.96741684e+00],
       [-6.72862084e-02,  7.88877919e-02, -4.29435606e-01,
        -2.13953953e-02, -7.07729329e-03,  7.34966660e-03,
         6.67244342e-03,  3.32845976e-02,  4.14564633e-01,
         5.44997734e-01,  6.56457716e-03, -6.43613323e+00],
       [-3.26597108e-02, -1.29333052e-01,  1.51016479e-01,
        -3.87650307e-02, -1.88048008e-02, -2.54111645e-03,
         1.75897415e-02, -2.93425917e-02, -3.77767517e-01,
        -9.56601710e-01, -3.68432459e-01, -3.67932451e+00],
       [ 1.90939550e-02, -2.24695203e-01, -1.99367006e-01,
        -4.06122995e-02,  9.15810191e-03,  1.01286691e-02,
         6.33642398e-03, -3.25180365e-03,  4.40314477e-02,
        -6.72811494e-02, -2.66860033e-02,  1.85072025e+00],
       [ 8.67631725e-02, -8.72705150e-01,  2.5266565

In [40]:
# Step 7 : predict model
y_pred = model.predict(X_test)

In [44]:
y_pred

array([6, 6, 6, 6, 6, 6, 5, 6, 5, 6, 5, 6, 7, 6, 6, 5, 7, 5, 5, 6, 5, 7,
       5, 5, 6, 6, 6, 5, 6, 5, 6, 5, 7, 5, 7, 6, 6, 5, 6, 5, 6, 5, 6, 6,
       7, 6, 6, 6, 5, 5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 5, 6, 6, 6, 6, 6, 5,
       6, 5, 6, 6, 5, 6, 6, 5, 5, 6, 6, 5, 6, 7, 4, 6, 5, 6, 5, 6, 5, 7,
       5, 5, 5, 5, 5, 7, 6, 6, 4, 5, 5, 6, 5, 5, 7, 6, 6, 5, 5, 6, 7, 6,
       7, 5, 5, 6, 5, 6, 7, 6, 5, 5, 6, 6, 5, 5, 6, 5, 5, 5, 7, 6, 7, 5,
       5, 5, 5, 6, 5, 6, 5, 5, 5, 7, 5, 5, 5, 6, 7, 5, 5, 6, 5, 5, 6, 5,
       7, 6, 5, 6, 5, 5, 5, 5, 6, 5, 5, 5, 6, 5, 5, 6, 6, 6, 6, 5, 5, 6,
       5, 5, 6, 5, 4, 5, 5, 6, 5, 4, 6, 7, 5, 5, 5, 5, 6, 6, 5, 6, 6, 5,
       5, 6, 5, 6, 6, 5, 6, 5, 5, 7, 7, 5, 6, 7, 6, 6, 6, 6, 5, 5, 6, 7,
       5, 6, 6, 5, 5, 5, 5, 5, 5, 6, 7, 6, 6, 5, 7, 5, 5, 5, 7, 5, 6, 5,
       7, 5, 5, 6, 5, 6, 5, 5, 6, 6, 5, 5, 5, 5, 6, 5, 5, 5, 5, 5, 5, 6,
       6, 6, 7, 5, 5, 7, 7, 6, 5, 5, 6, 5, 6, 6, 5, 6, 6, 6, 6, 5, 7, 7,
       6, 5, 6, 7, 5, 7, 7, 5, 6, 6, 7, 5, 6, 5, 7,

In [45]:
# Step 8 : model accuracy
from sklearn.metrics import confusion_matrix, accuracy_score, classification_report

In [46]:
confusion_matrix(y_test,y_pred)

array([[  0,   1,   0,   0,   0,   0],
       [  0,   3,   7,   0,   0,   0],
       [  0,   0, 157,   0,   0,   0],
       [  0,   0,   0, 132,   0,   0],
       [  0,   0,   0,   0,  40,   0],
       [  0,   0,   0,   0,   3,   0]])

In [47]:
accuracy_score(y_test,y_pred)

0.967930029154519

In [48]:
print(classification_report(y_test,y_pred))

              precision    recall  f1-score   support

           3       0.00      0.00      0.00         1
           4       0.75      0.30      0.43        10
           5       0.96      1.00      0.98       157
           6       1.00      1.00      1.00       132
           7       0.93      1.00      0.96        40
           8       0.00      0.00      0.00         3

    accuracy                           0.97       343
   macro avg       0.61      0.55      0.56       343
weighted avg       0.95      0.97      0.96       343



/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
/usr/local/lib/python3.10/dist-packages/sklearn/metrics/_classification.py:1344: UndefinedMetricWarning: Precision and F-score are ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, msg_start, len(result))
